// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYvtwfu5Xu_Dtpu2_7ZGvZnG4hnXkp0Y',
    appId: '1:803085119993:android:cce09a4f3c11fef942cd28',
    messagingSenderId: '803085119993',
    projectId: 'kpssharitasi-893a6',
    storageBucket: 'kpssharitasi-893a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZMwqVsmvX30oD-ey_Lwgpm7CiS8QOpQ',
    appId: '1:803085119993:ios:a7496e365847cc9342cd28',
    messagingSenderId: '803085119993',
    projectId: 'kpssharitasi-893a6',
    storageBucket: 'kpssharitasi-893a6.firebasestorage.app',
    iosClientId: '803085119993-2fatbj61gcfq4f1sk4pt3mudk8du9rld.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpssHaritasi',
  );
}
